version: '3.7'

services: 
  local-social-api:
    image: local-social-api:dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
        - 3002:8000
  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
